openapi: 3.0.0
info:
  title: Liceo TP API
  version: v1

servers:
  - url: /api/v1

paths:
  /auth/login:
    post:
      summary: Login (token)
  /alumnos:
    get:
      summary: Lista de alumnos (paginada)
      parameters:
        - in: query
          name: curso_id
          schema:
            type: integer
  /asistencias:
    post:
      summary: Crear asistencias masivas
